import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import Layout from "@/components/Layout/Layout";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body>
            <AppRouterCacheProvider>
               <ThemeProvider theme={theme}>
                  {/* <LocalizationProvider dateAdapter={AdapterDayjs}> */}
                  <Layout>{children}</Layout>
                  {/* </LocalizationProvider> */}
               </ThemeProvider>
            </AppRouterCacheProvider>
         </body>
      </html>
   );
}
